name: Burger Builder - Full Deployment (Infrastructure + Backend App + Frontend App)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_HOST: burgerbuilderacr.azurecr.io
  RESOURCE_GROUP: bb-selwan-rg
  BACKEND_APP: burgerbuilder-backend
  FRONTEND_APP: burgerbuilder-frontend
  LOCATION: swedencentral
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_acr_password: ${{ secrets.ACR_PASSWORD }}

jobs:
  
  # 1️ - Terraform's Infrastructure Deployment
  
  infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Initializing Terraform
        run: terraform init
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -lock=false -out terraform.tfplan
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Applying Terraform
        run: terraform apply -auto-approve=true -lock-timeout=30s -input=false terraform.tfplan
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

  
  # 2️ - Deploying the Backend
  
  backend:
    runs-on: ubuntu-latest
    needs: infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: ACR Login
        uses: docker/login-action@v3
        with:
          registry: burgerbuilderacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Building the Backend Image
        run: |
          cd backend
          mvn clean package -DskipTests
          docker build -t $ACR_HOST/backend:latest .

      - name: Pushing the Backend Image
        run: docker push $ACR_HOST/backend:latest

      - name: Deploying the backend container app
        run: |
          az containerapp update \
            --name $BACKEND_APP \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_HOST/backend:latest

  
  # 3️ - Deploying the Frontend
  
  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: ACR Login
        uses: docker/login-action@v3
        with:
          registry: burgerbuilderacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD}}

      - name: Building the frontend app
        run: |
          cd frontend
          npm ci
           echo "VITE_API_BASE_URL=http://135.225.92.111/" > .env
          cat .env
          npm run build

      - name: Building the frontend image
        run: |
          cd frontend
          docker build -t $ACR_HOST/frontend:latest .

      - name: Pushing the frontend image
        run: docker push $ACR_HOST/frontend:latest

      - name: Deploying the frontend container app
        run: |
          az containerapp update \
            --name $FRONTEND_APP \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_HOST/frontend:latest
